language: java
jdk:
- oraclejdk8
sudo: false
before_install:
- cp releng/maven_settings.xml ~/.m2/settings.xml
- sh releng/prepare_signing.sh
install: mvn install -Prelease -DskipTests=true -B -q -e
before_script:
- export MAVEN_OPTS="-Xmx512m -XX:MaxMetaspaceSize=512m"
script: mvn -q -B -e test
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: ovVGg8aFnpf/AyeMfc6KZ6xIwImi0n0Chxo5xjgTXymIDT1S8cNLB0xcyTFEmPqu7mzwW+cz/MIASfiZQkyzfJNl0UAQJRVHhymzqAqoDsRHximzl5+20JXtuMp72B9JgOMl1eL5gWFZw2AOJsv4UolEPZFyFDLN7riB4W6srWomdlqbnybBnA9HOIHU703NBOkQBXzZeyRv/mX819IpJ5nDneOLMteQLLUfc7pRpPyCqbv0ihvBTwsnheg/TzVgAyHZjb9c8iQcYZdgB8aXWS/NCSnRkJGYyUxuwauLV3t8qaiiU9mQnqXt6TtMo1WE7H8dqHjsAdoEc/vkKCGkHY4xtlJcP9DVbB+DuPoOO+DFgz5dSmRiHzZuLyc1f4lOTfgUqn4lmlNo7razZxpO1kB/FYY+NU+A6BsqrD+GBsE/7Mn3260z6T2LQV+Xt8sXzFxLdGlTWSf1i3CXSNPw1vBr4RTl8c2TeS1A/wI7dSMjHU/HUoUxWVHCXSvh7dvb3CArh7TtycW6vmZjGWWbmmBpyN50xgD9eC88JtehqMNh9hBmgdczb/CkrYQpFDQzsXc2J1hpKW7vInbqg1/22uaqH1O1522MzhVK2M3f3pCKbKUBhocIYGIJTwiSUvsfrXtP+8TNXlutCDSvy5BN4XVv//jrJntKh2YqJSMBrRU=
  file_glob: true
  file:
  - target/*.jar
  - target/*.jar.asc
  - target/*.pom
  - target/*.pom.asc
  on:
    repo: stheves/denon4j
    tags: true
    all_branches: true
- provider: script
  script: mvn -q -B -e deploy -Prelease -DskipTests=true
  skip_cleanup: true
  on:
    repo: stheves/denon4j
    tags: true
    all_branches: true
cache:
  directories:
  - ~/.m2/repository
notifications:
  email:
  - sascha.theves@gmail.com
env:
  global:
  - secure: JdI1nnAb9X9AWcQoq68e/cIPGZzTCeXcFJ59/73zawGQI/eQ699BY9NmBIfnEInSCpBShXlBLLUnOQjrNqj0znnl6UNQWMUH3BsbbZKOzUkkEnokMmPIJTTK9Q7YCN36wKg750M7LFYJt5NpjNhTVSTNi7U8+Ts59TOSs7Z0K5psmoidrUWAaWEIn7QhVqq5OXfeJIa1ogHs7joMxD3IRtJRYR8P0uVSgQFm0ZfX8qWoZZfNiCYx8He8J5C8gGNcdeTOujuRPzoRwdFTA2N/mQ7rtv8kBeaG8erjGdPCeyuRgAhapuizsRS19eM6sG6LK7nP2b6QujWmuhBVvxDnF4+qhtNEfZi7fZ5876nx5L1e352PwfclpL6e+HSbXxumbaiJ7CHH36C1TDgDaEFSDlbBHPRC0Uz6BdGYE4Nad9bJXvGtlHHQD+31GtHmZyC+xihjE5G/2aTUKTf/zuD3E1SeNYBYSGisDrpg6Jm5TwY5UJtya2npP1g1NLVQyQLkbkEM2mw6wXHsM4Op3O35FqDj7r0uPsKZfRc/m4+lUF+O98al2+/DxdM0sDSg35O5a8dE6xAdiOEtZ8lWGYiiK2hEXdrDeC57KhWuwAHbTyA24T7uaGiQborpX82EfF5+g75ZwQuQp4XYwQd5aYUJUBUaZ78UsW0gr1nCSgmfp3c=
  - secure: bYoGyqiD9KHyX8VtLQEYkbkPuRjgfVwqE2g/kpwBBFg2z92FTZrkBzhQHh4VFeGNFJefAUTQ6k6wE253R4/GlHqoznNRcJrmoc5B+Qv6axHlzzwAno0JvcLgIW/mBUbTkg2TRoWscVddfK63aDrg25GuwtjD9lFwOQuqTEKPPXKVxQdlz9GC/xfsJ+pZ0mt67MS78YkaxhUtkyuVqiZQYZl6Xz+n6nDcvzg8tL5dRF6RuP4fybauw0RvcqoM9v193qNXTYDkKpeBKTtAnE4gzZdvQEuYEOlUDjjhmIQzzG+J0dR2/WTj+Opiq54l/oVCqoJr4ktTdXRknKb8weZKb7Qs95EV7e4Z5qYrsicDdCpD3XnTowldHpvvHDrEj+clfqpN5vqtztk02k9G3HA1XiWtYDzErXnXg9dI+phdB4pntEHqgBok7j11/GGJ6SdF3LG4xH9ooEDQwMcswz4gIdWXflvdvozop6Z6igXJMkSz8/1kzSFiqGWW43tXCKzscw1WvvVbf4n61rGEqJG5PI81b0r+n7eM8an852RXVHS8HFT9nFtkkb11yaoinQFHXZZ4T+gPO8nLGTk7HlWBimvX97TyLjbWXqg2ExUgt5GwhCSs/4/8OyiaHUDCZ0K1PiYIR8u1a62RnVLubtVnaUUpduM/XxiQeT51mOvmA/A=
  - secure: J11zqa9MFkh3tMMcvCFIwN3/nfEVYEsMwEHNLb+pqiGnxTjXneTS7GAIwHDfLlvqfgBVXLVQy1EWRwz6i6+Ozs3LwFpbYF4A8R/TP/Hp5dE1sBgmZ4yX5mXUQgcWBKwzwEpx0UP7zztpoEb5Bi5EfCrD6iNUV7PQnVA3jr1pt3ImOzaT3hkuT55tI0a8vgwsIfUJMbMU6f5S2Os6NAyiImhxFt+dDo7fpXo4kd3Ur+tC4Y93HN4eed+UhKNk/IQ7J2aKWhfX9DbuYQ6NeucRWXqHWZ3t2EVpARtpqUEJramCfM1AvEy6kd0tRUP0pfrWd/Ji17KMr2OaxI7nt4f9JboJgNJCg4P1VgH7Zc+NIXPGa3SvLc6YXRb0jA5GAu9DLe3S19cWLWp2JPDq14TyOdCUuYa5hToszSPouGOZ6ahZ/yTFop1ixWpvXqB+rz55VjE6qwALK9C5Z5VVelad7EFaBODdOxYWStIk0NFuJyYOsZELHTy9A9DVCbsitUDGOjVe4xx+JLyzT37xMSxjx8Qlo9eknTF6kA9DS9Kl1EortDRWPJNUIV1b8MVj5tXmTjv/+AZI9xO7xDyRa7uvVy6R8D+41W8bklbtSsPC8U07CoEDo68U6nt2V0mvbORexFkpB8NzItDzze/3D4Kc9rxK1BZLrjSwI6crZAUY5cg=
  - secure: WhzNjNuC0ZYGK4Wo8yZ4fSEFjUDIDkYZWnXht7bMEKk9hcuCH+ecLJD/CP5K83yhBy4GzqP8Sj63fbXiLYpxTzyixGihpDDo6EoAFNJ0O4j8TneSDYVZKfogDU7hCaQiLB1/WzxbQHJef4bTUrLdiK7VnjXzJiMjdA4X+WEdXD3fGD2q4wuoUGVPhp5ynZAbsFogIBLki3fM1UzA1nlOKA6rYjqrLChd00U7W2vmb7m+usEBnOoGiYZpx2gN2niO8cZfk2tOSPNokWaENpwqKXBrg7gKxNHuvpsg05X+G83+7CaEddcuHJZgM4aVjP5faZnU9q5jsq0ShMieXTqza9qf2GIxxzXaaH39LMQZke9Wf33SFaJvNo03cJ6rVmMJNwungGHi+1LKkNRy4zbwu4k0Vexz9+cnbxSrtXRZuHme5tGQw93P6G9l6Gu2iOepMnnoWNRgxOGiYJ5htn6Ea0SI8A+l9SGeqHlbQO93xWhfslLYI2cloMUS+FJYzGPRncMtuUj9vw18oBGJq8RnzBdmqENckSxeOI1of5oF2JdOYRrqGPeeOj1FCkzvQ74wTa3Sf+HfK/JKwY9Tap7HGkmbUlGo809FA+vw8DqWmajDUWjjMoUzcd7XuIOkj7DbWD57R+mXnH9GhJgDuHzLHg0SvkclPfGJmQhvAm3Rbjc=
