language: java
jdk:
- oraclejdk8
sudo: false
before_script:
- export MAVEN_OPTS="-Xmx512m -XX:MaxMetaspaceSize=512m"
script: mvn -q -B -e clean package
before_deploy:
- export ARTIFACT=$(ls target/denon4j.jar)
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ovVGg8aFnpf/AyeMfc6KZ6xIwImi0n0Chxo5xjgTXymIDT1S8cNLB0xcyTFEmPqu7mzwW+cz/MIASfiZQkyzfJNl0UAQJRVHhymzqAqoDsRHximzl5+20JXtuMp72B9JgOMl1eL5gWFZw2AOJsv4UolEPZFyFDLN7riB4W6srWomdlqbnybBnA9HOIHU703NBOkQBXzZeyRv/mX819IpJ5nDneOLMteQLLUfc7pRpPyCqbv0ihvBTwsnheg/TzVgAyHZjb9c8iQcYZdgB8aXWS/NCSnRkJGYyUxuwauLV3t8qaiiU9mQnqXt6TtMo1WE7H8dqHjsAdoEc/vkKCGkHY4xtlJcP9DVbB+DuPoOO+DFgz5dSmRiHzZuLyc1f4lOTfgUqn4lmlNo7razZxpO1kB/FYY+NU+A6BsqrD+GBsE/7Mn3260z6T2LQV+Xt8sXzFxLdGlTWSf1i3CXSNPw1vBr4RTl8c2TeS1A/wI7dSMjHU/HUoUxWVHCXSvh7dvb3CArh7TtycW6vmZjGWWbmmBpyN50xgD9eC88JtehqMNh9hBmgdczb/CkrYQpFDQzsXc2J1hpKW7vInbqg1/22uaqH1O1522MzhVK2M3f3pCKbKUBhocIYGIJTwiSUvsfrXtP+8TNXlutCDSvy5BN4XVv//jrJntKh2YqJSMBrRU=
  file: "${ARTIFACT}"
  on:
    repo: stheves/denon4j
    tags: true
    all_branches: true

notifications:
  email:
  - sascha.theves@gmail.com
